image: node:14-alpine # use nodejs v14 LTS
cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  script:
    - mpx next export
  artifacts:
    paths:
      - out
  only:
    - master